### ISSUE TITLE
Segfault when calling a method when `this` is null 

### ISSUE THREAD

**Issue by jcmonnin** [pmed/v8pp#106]
See test case: jcmonnin/v8pp@8c9db4544a08a8b20b008cf1339f59b71696c431

When  `this` doesn't reference the actual instance, v8pp resolves the unwarp to a nullptr and then calls the method on the null pointer which causes a segfault.

The script shouldn't be able to crash the host application, so I think there should be a runtime check that results in a JavaScript error.

Let me know if you prefer to have a full patch proposal instead of just this incomplete test case.

**Comment by pmed** [comment]
Hi Jean-Claude,

Thank you for the bug reporting!

Yes, this is a good idea to throw a JavaScript exception back to the
script, instead of the host application crashing.

If you already have a fix for this issue, I would happy to merge it.

вт, 26 мар. 2019 г., 16:35 Jean-Claude Monnin <notifications@github.com>:

**Comment by jcmonnin** [comment]
Hi Pavel,

I currently don't have a fix that is ready, but I can try to make one. I keep you updated.
