### ISSUE TITLE
c++11 json and v8pp

### ISSUE THREAD

**Issue by vinnitu** [pmed/v8pp#12]
It will be very useful to add conversion between v8 and json (https://github.com/nlohmann/json)
What do you think about?

**Comment by pmed** [comment]
There is a `JSON` object in V8 global object with `stringify()` and `parse()` functions.

As I remember, since V8 version 3.14 JSON parser is also exposed into C++ API, look at `v8::JSON::Parse()` function. I wonder why they didn't exposed the `stringify` function into C++

Anyway, in one project I used it like this:

```c++

/// V8 value as JSON
std::string json_str(v8::Isolate* isolate, v8::Handle<v8::Value> value)
{
	v8::HandleScope scope(isolate);

	v8::Local<v8::Object> json = isolate->GetCurrentContext()->Global()->Get(v8::String::NewFromUtf8(isolate, "JSON"))->ToObject();
	v8::Local<v8::Function> stringify = json->Get(v8::String::NewFromUtf8(isolate, "stringify")).As<v8::Function>();

	v8::Local<v8::Value> result = stringify->Call(json, 1, &value);
	v8::String::Utf8Value const str(result);
	return *str;
}

/// Parse JSON stringinto V8 value
v8::Handle<v8::Value> json_parse(v8::Isolate* isolate, std::string const& str)
{
	v8::EscapableHandleScope scope(isolate);

	v8::Local<v8::Object> json = isolate->GetCurrentContext()->Global()->Get(v8::String::NewFromUtf8(isolate, "JSON"))->ToObject();
	v8::Local<v8::Function> parse = json->Get(v8::String::NewFromUtf8(isolate, "parse")).As<v8::Function>();

	v8::Local<v8::Value> value = v8::String::NewFromUtf8(isolate, str.data(), str.size());

	v8::TryCatch try_catch;
	v8::Local<v8::Value> result = parse->Call(json, 1, &value);
	if (try_catch.HasCaught())
	{
		result = value;
	}
	return scope.Escape(result);
}
```

Additionaly `JSON` object, its `parse` and `stringify` functions may be cached in persistent handles to not query them from global scope on each call. 

Probably such functions may be added as utlities into v8pp.

**Comment by vinnitu** [comment]
Ok, thank You for idea

**Comment by nathanieltagg** [comment]
This is true, but I can image projects where a large JSON document is created in C++ (using the fast and easy and weightless nlohmann::json) and then you want to convert that object to a v8 object without passing it through a stringify-then-reparse sequence. I found this issue by looking for it.  But, maybe that's a rare case.

**Comment by pmed** [comment]
Hi @nathanieltagg 

If you want to convert a C++ object to a `v8::Object` instance, there is no need to stringify the C++ object to JSON and to parse it back to V8 object. You may use [`v8:::set_option()`](http://pmed.github.io/v8pp/utilities.html#set-an-attribute-in-v8-object) function to set the V8 object properties, or to  specialize [`v8pp::convert<T>`](http://pmed.github.io/v8pp/convert.html#user-defined-types) template for such a C++ type.

You can also find another `convert<>` example in the `test_convert` case: https://github.com/pmed/v8pp/blob/master/test/test_convert.cpp#L72-L122

**Comment by nathanieltagg** [comment]
Sorry, I think I posted in the wrong issue tracker. :)

**Comment by nikovacs** [comment]
I am in a situation where I would really benefit from being able to expose an existing `nlohmann::json` object to v8, thus allowing the assignment and retrieval of values from C++ or JS. For example, it would be nice to do something like:
```cpp
json_instance["key"] = 4;
```

and in JS be able to:
```javascript
// assume json object is exposed as `json`
let value = json["key"] // 4
```

Is this something that is feasible? Or would you suggest taking the above approach of always dumping and re-parsing the json when a change is made?

**Comment by pmed** [comment]
Hi Nikolas,

Instead of Json stringy/parse you could create a converter `v8pp<nlohmann::json>` specialisation (see https://github.com/pmed/v8pp/issues/12#issuecomment-468716222)

It seems the data conversion is unavoidable here, since `nlohmann::json` and `v8::Object` are completely different entities.
