### ISSUE TITLE
compilation error: 'this' was not captured for lambda function

### ISSUE THREAD

**Issue by nouknouk** [pmed/v8pp#16]
Hi,

and first, thanks a lot for this amazing piece of code :-)

When I try to build my app including the v8pp 'class' headers, I get the following error.
Would you have any idea about what's happening ?

Thanks in advance.

###### compile output:

```
g++ -c -m64 -pipe -g -w -std=c++11 -I../../3rdparty/desktop/include/v8 -Isrc -o build/desktop/obj/javascriptTest.o src/javascriptTest.cpp

In file included from src/javascriptTest.cpp:21:0:
../../main/src/javascript/v8pp/class.hpp: In instantiation of ‘v8pp::detail::class_singleton<T>::class_singleton(v8::Isolate*, v8pp::detail::class_info::type_index) [with T = Point; v8pp::detail::class_info::type_index = unsigned int]::<lambda(const v8::FunctionCallbackInfo<v8::Value>&)>’:
../../main/src/javascript/v8pp/class.hpp:178:5:   required from ‘struct v8pp::detail::class_singleton<T>::class_singleton(v8::Isolate*, v8pp::detail::class_info::type_index) [with T = Point; v8pp::detail::class_info::type_index = unsigned int]::<lambda(const class v8::FunctionCallbackInfo<v8::Value>&)>’
../../main/src/javascript/v8pp/class.hpp:189:5:   required from ‘v8pp::detail::class_singleton<T>::class_singleton(v8::Isolate*, v8pp::detail::class_info::type_index) [with T = Point; v8pp::detail::class_info::type_index = unsigned int]’
../../main/src/javascript/v8pp/class.hpp:261:4:   required from ‘static v8pp::detail::class_singleton<T>& v8pp::detail::class_singleton<T>::instance(v8::Isolate*) [with T = Point; v8pp::detail::class_singleton<T> = v8pp::detail::class_singleton<Point>]’
../../main/src/javascript/v8pp/class.hpp:369:56:   required from ‘v8pp::class_<T>::class_(v8::Isolate*) [with T = Point]’
src/javascriptTest.cpp:71:42:   required from here
../../main/src/javascript/v8pp/class.hpp:183:74: error: ‘this’ was not captured for this lambda function
../../main/src/javascript/v8pp/class.hpp:183:74: error: return-statement with a value, in function returning 'void' [-fpermissive]
make: *** [build/desktop/obj/javascriptTest.o] Error 1
```
###### details:
* `file included from src/javascriptTest.cpp:21:0` being: `v8pp/class.hpp`

* `src/javascriptTest.cpp:71:42: required from here` being
```
v8pp::class_<Point> point_class(isolate);
```
(with Point being a basic int 2d-coord(x,y) class, no template or anything else)
###### my environment:
```
g++ (Debian 4.7.2-5) 4.7.2
#define V8_MAJOR_VERSION 4
#define V8_MINOR_VERSION 5
#define V8_BUILD_NUMBER 103
#define V8_PATCH_LEVEL 30
```

**Comment by pmed** [comment]
Hi, thanks!

I haven't tested the library with GCC 4.7 and I have no such a version right now. I may only speculate that compiler tries to use `this` for a static function `class_singleton::instance()` in that lambda.

Please try to specify full name for the `instance` function() in [line 183 in v8pp/class.hpp](https://github.com/pmed/v8pp/blob/master/v8pp/class.hpp#L183):

```c++
args.GetReturnValue().Set(class_singleton::instance(isolate).wrap_object(args));
```

I found this is a bug in GCC 4.6 (and in 4.7 too): http://stackoverflow.com/questions/4940259/lambdas-require-capturing-this-to-call-static-member-function

Unfortunately, you can not capture `this` for the lambda, since it will become incompatible with `v8::FunctionCallback` type.

The same error likely will occur in a lambda below in `class_singleton::wrap()` function.

As a workaround you may use additional static functions instead of these lambdas.

But I think the best way is consider to use GCC 4.8 or newer :-)

**Comment by nouknouk** [comment]
You're right, the root cause was the version of GCC. After an upgrade, the problem solved by itself.
Maybe it could be a good thing to mention explicitely the issue with GCC 4.7 in the main page of the project ?

Thanks.

**Comment by pmed** [comment]
A list of tested compilers is already on top README:

>The library has been tested on:
>
>* Microsoft Visual C++ 2013 (Windows 7/8)
>* GCC 4.8.1 (Ubuntu 13.10 with Linux kernel 3.11.0)
>* Clang 3.5 (Mac OS X 10.2)

**Comment by nouknouk** [comment]
Yes, I saw it. I just tought maybe adding the incompability expliciting would also help other users (like me).
