### ISSUE TITLE
Doesn't work with V8 6.7.288.46

### ISSUE THREAD

**Issue by ncook-vero** [pmed/v8pp#78]
Hi there,

I found a problem in class.hpp on line 223 when using v8pp with the V8 version listed in the title (current stable version).

The fix is simple, but it seems this is a breaking change in the V8 API.
I can submit a pull request with a fix if you desire, but I am not sure on how v8pp handles V8 versions (does it alter behaviour depending on V8 version? - Is this a problem that has been faced before?)

Regards,

Nathan

**Comment by pmed** [comment]
Hi Nathan,

Could you please supply the error message, because I don't see anything breaking V8 version 6.7 there at https://github.com/pmed/v8pp/blob/master/v8pp/class.hpp#L223

**Comment by ncook-vero** [comment]
Hi @pmed :)

You are quite correct, I see v8pp has seen some change since our organisation found it.
I can see you've already fixed the problem I'd encountered and are way ahead of me (you fixed it at line 236).

Forgive me! I wasn't sure which version of v8pp we have, I think we'll just update/upgrade to your newest work.
 
BTW I wasn't trying to say 'you broke V8', I just meant their API had changed a lot. (We're on v5.9 and looking at upgrading).

Thank you for subtly explaining that v8pp we have is old. 👍

**Comment by pmed** [comment]
Hi Nathan,

You are welcome :) I didn't mean that V8 is broken; it has a number of deprecations in API, and from time to time changes. So upgrading to newer V8 version may not be simple.

The v8pp project has Travis CI build with various V8 versions up to 6.6. Unfortunately I couldn't find .deb packages for more recent V8 versions, and I have no spare resources now to maintain these builds and releases.

Anyways, thank you for reporting. I will think about updating Appveyr CI with newer V8 versions, since I have NuGet packages for V8.

Best regards,
Pavel

**Comment by ncook-vero** [comment]
Hi Pavel,

At least upgrading v8pp will be easy. :)
And probably the change I see in V8 happened many versions ago.. 

Nathan
